name: Release Please

on:
  push:
    branches: [main]

jobs:
  release-please:
    uses: wcmchenry3-stack/.github/.github/workflows/called-release-please.yml@main
    permissions:
      contents: write
      pull-requests: write
